return {
    singleton = {
        script = 'msw/world_server_entry',
        module = 'msw/world_server_component',
        bridge = 'msw/world_server_bridge',
        attachTo = '/server_runtime',
        runtimeContract = {
            worldScope = 'authoritative_server_runtime',
            ownership = 'world/channel/runtime scoped',
            lifecycle = { 'bootstrap', 'tick', 'player_enter', 'player_leave', 'map_load', 'reconcile', 'shutdown' },
            bindings = { 'player', 'world', 'channel', 'map' },
            sync = { 'delta_state', 'entity_lifecycle', 'event_routing', 'reconciliation' },
        },
        attachToAliases = {
            'server_runtime',
            'common/server_runtime',
        },
        events = {
            { scope = 'Service', target = 'UserService', eventName = 'UserEnterEvent' },
            { scope = 'Service', target = 'UserService', eventName = 'UserLeaveEvent' },
        },
    },
    serverMethods = {
        'GetPlayerState',
        'GetMapState',
        'GetStateDelta',
        'GetBridgeDiagnostics',
        'ReconcileRuntimeState',
        'DispatchRuntimeEvent',
        'RoutePlayerAction',
        'HandleGatewayRequest',
        'GetEventStream',
        'AttackMob',
        'PickupDrop',
        'DamageBoss',
        'AcceptQuest',
        'TurnInQuest',
        'BuyFromNpc',
        'SellToNpc',
        'EquipItem',
        'UnequipItem',
        'ChangeMap',
        'AllocateStat',
        'PromoteJob',
        'LearnSkill',
        'CastSkill',
        'EnhanceEquipment',
        'CreateParty',
        'CreateGuild',
        'AddFriend',
        'TradeMesos',
        'ListAuction',
        'CraftItem',
        'OpenDialogue',
        'ChannelTransfer',
        'GetEconomyReport',
        'AdminStatus',
        'GetBuildRecommendation',
        'GetTutorialState',
        'ListPartyFinder',
        'CreateRaid',
    },
}
