package.path = package.path .. ';./?.lua;../?.lua'

local ServerBootstrap = require('scripts.server_bootstrap')

local world = ServerBootstrap.boot('.')
world:createPlayer('ops-a')
world:createPlayer('ops-b')
local status = world:adminStatus()
assert(status.consistent == true, 'world consistency failed')
assert(status.replay.ok == true, 'replay determinism failed')
local control = world:getControlPlaneReport()
assert(control.cluster.worldId == world.runtimeIdentity.worldId, 'cluster mismatch')
assert(control.shards['shard-main'] ~= nil, 'missing shard')
assert(type(control.routing.latestDecision) == 'table' or control.routing.latestDecision == nil, 'routing surface missing')
assert(type(control.snapshots) == 'table', 'snapshot summary missing')
assert(type(control.metrics) == 'table', 'metrics aggregate missing')
assert(type(control.operatorSurface) == 'table', 'operator surface missing')
assert(control.operatorSurface.tuningPoints.congestionRoutingThreshold ~= nil, 'routing tuning point missing')
assert(control.operatorSurface.ownership ~= nil, 'ownership surface missing')
assert(control.operatorSurface.ownership.routingOwner == 'channel_router', 'routing owner missing')
assert(control.operatorSurface.mutationBoundaries ~= nil, 'mutation boundary surface missing')
assert(control.operatorSurface.economy.mutationBoundaries ~= nil, 'economy mutation boundary surface missing')
print('ops_control_plane_test: ok')
